; 0-4 dŸwiêki inventory podnoszenie-upuszcznie itd...
; 5-7 dŸwiêki t³umików broni

[main]
;to ma byc na prawdê maksymalny numer dŸwiêku
max_num_sound = 7

[sound_0]
name = z ziemi
file = Inventory\\Item_Take.wav

[sound_1]
name = na ziemie
file = Inventory\\Item_Get.wav

[sound_2]
name = z inv do mysz
file = Inventory\\Item_Drop.wav

[sound_3]
name = z mysz do inv
file = Inventory\\Item_Put.wav    

[sound_4]
name = increase stack undr mouse
file = Inventory\\Item_Stack.wav

[sound_5]
name = silencer_0
file = Inventory\\pistol-silencer.wav

[sound_6]
name = silencer_1
file = Inventory\\colt-silencer.wav   

[sound_7]
name = silencer_2
file = Inventory\\colt-silencer2.wav

[sound_8]
name = flip mysz - inv
file = Inventory\\colt-silencer2.wav

[sound_9]
name = chunk
file = Inventory\\colt-silencer1.wav
