[FONTS]
;Maximum 9 fontow (z zakresu 0 - 9)
FONTS   = 3

FONT1   = 2
FONT1LF = 70
FONT1LL = 30

FONT2   = 2
FONT2LF = 40
FONT2LL = 20

FONT3   = 3
FONT3LF = 10
FONT3LL = 10

[TEXT]
;Maximum 128 linii po 128 znakow

;Hipotetyczna wielkos wszystkich creditsow w Pixelach
CANVAS = 4400; 
;Ilosc Wszystkich Linii
LINES=70

;Postac LXXX=Nrfontu (jedna cyfra!!!),text

L001=1,CREDITS
//L001 = 3 lub 5,credits

L002=2,Production Supervisors
L003=3,Adam Mikociak
L004=3,Alicja Szmukala

L005=2,Game Designer
L006=3,Lucjan Mikociak

L007=2,Senior Programmer
L008=3,Jan Jasinski

L009=2,Assistant Game Designer
L010=3,Pawel Dabrowski

L011=2,Lead Programmer
L012=3,Jakub Laczny

L013=2,Programmers
L014=3,Szymon Kubisiak
L015=3,Wiktoryn Zerebecki
L016=3,Jakub Frankowski
L017=3,Lukasz Lesicki
L018=3,Marcin Jaskula
L019=3,Miloslaw Frey

L020=2,Lead 3D Artists
L021=3,Piotr Kolasinski
L022=3,Tomasz Tyrka

L023=2,3D Modelling
L024=3,Stanislaw Marek
L025=3,Arek Ojczyk
L026=3,Pawel Hynek
L027=3,Dariusz Frymus
L028=3,Michal Jedrzejowski
L029=3,Marcin Dzaman
L030=3,Piotr Nowokunski
L031=3,Krzysztof Lorczyk
L032=3,Bartlomiej Berdys

L033=2,3D Animations
L034=3,Tomasz Tyrka
L035=3,Malgorzta Kotnowska

L036=2,Concept Art
L037=3,Stanistaw Marek

L038=2,Storyline
L039=3,Lucjan Mikociak
L040=3,Berdysz
L041=3,Leon
L042=3,Michal Rokita

L043=2,Level Designer
L044=3,Pawel Dabrowski

L045=2,Music & SFX
L046=3,Adam Skorupa

L047=2,Additional Music
L048=3,Markus Holler

L049=2,Additional SFX
L050=3,Fabian Del Priore

L051=2,Office Managment
L052=3,Anna Rutkowska

L053=2,Game Testers
L054=3,Jakub Jasinski
L055=3,Tomasz Prochownik
L056=3,Pawel Puchala
L057=3,Marcin Kawa
L058=3,Jakub Tadeusz Janicki

L059=2,Special Thanks to:
L060=3,Renata Jasinska
L061=3,Barbara Laczny
L062=3,Joanna Dabrowska
L063=3,Monika Hanzlik
L064=3,Malgorzata Ferens
L065=3,Gabriela Pederska
L066=3,Tomasz Majkowski 
L067=3,Martinez
L068=3,Jan Marek
L069=3,Tomasz Chojna
L070=3,Michal Madej

