[FONTS]
;Maximum 9 fontow (z zakresu 0 - 9)
FONTS   = 4
; Numer Fontu z fonts.ini
FONT1   = 2
; ilosc Pixeli przed (liczone od srodka napisu)
FONT1LF = 15
;ilosc pixeli po (liczone od srodka napisu)
FONT1LL = 30

FONT2   = 2
FONT2LF = 40
FONT2LL = 20

FONT3   = 3
FONT3LF = 10
FONT3LL = 10

FONT4	= 2
FONT4LF = 70
FONT4LL = 30

[TEXT]
;Maximum 128 linii po 128 znakow

;Hipotetyczna wielkos wszystkich creditsow w Pixelach
CANVAS = 4400; 
;Ilosc Wszystkich Linii
LINES=121

;Postac LXXX=Nrfontu (jedna cyfra!!!),text

L001=1,CRÉDITOS
//L001 = 3 lub 5,credits

L002=2,Supervisores de producción
L003=3,Adam Mikociak
L004=3,Alicja Szmukala

L005=2,Diseñador del juego
L006=3,Lucjan Mikociak

L007=2,Programador sénior
L008=3,Jan Jasinski

L009=2,Ayudante de diseño del juego
L010=3,Pawel Dabrowski

L011=2,Programador jefe
L012=3,Jakub Laczny

L013=2,Programadores
L014=3,Szymon Kubisiak
L015=3,Wiktoryn Zerebecki
L016=3,Jakub Frankowski
L017=3,Lukasz Lesicki
L018=3,Marcin Jaskula
L019=3,Miloslaw Frey

L020=2,Artistas 3D jefes
L021=3,Piotr Kolasinski
L022=3,Tomasz Tyrka

L023=2,Modelado 3D
L024=3,Stanislaw Marek
L025=3,Arek Ojczyk
L026=3,Pawel Hynek
L027=3,Dariusz Frymus
L028=3,Michal Jedrzejowski
L029=3,Marcin Dzaman
L030=3,Piotr Nowokunski
L031=3,Krzysztof Lorczyk
L032=3,Bartlomiej Berdys

L033=2,Animaciones 3D
L034=3,Tomasz Tyrka
L035=3,Malgorzta Kotnowska

L036=2,Arte conceptual
L037=3,Stanistaw Marek

L038=2,Argumento
L039=3,Lucjan Mikociak
L040=3,Berdysz
L041=3,Leon
L042=3,Michal Rokita

L043=2,Diseñador de niveles
L044=3,Pawel Dabrowski

L045=2,Música y efectos de sonido
L046=3,Adam Skorupa

L047=2,Música adicional
L048=3,Markus Holler

L049=2,Efectos de sonido adicionales
L050=3,Fabian Del Priore

L051=2,Dirección de oficina
L052=3,Anna Rutkowska

L053=2,Probadores del juego
L054=3,Jakub Jasinski
L055=3,Tomasz Prochownik
L056=3,Pawel Puchala
L057=3,Marcin Kawa
L058=3,Jakub Tadeusz Janicki

L059=2,Agradecimientos especiales:
L060=3,Renata Jasinska
L061=3,Barbara Laczny
L062=3,Joanna Dabrowska
L063=3,Monika Hanzlik
L064=3,Malgorzata Ferens
L065=3,Gabriela Pederska
L066=3,Tomasz Majkowski 
L067=3,Martinez
L068=3,Jan Marek
L069=3,Tomasz Chojna
L070=3,Michal Madej

L071=4,JoWooD Productions Software AG
L072=2,Jefe de desarrollo
L073=3,Erik Simon
L074=2,Director internacional de producción y compras
L075=3,Fritz Neuhofer
L076=2,Director de gestión de productos
L077=3,Michael Hengst
L078=2,Jefe de producto
L079=3,Robert Alyazdi
L080=2,Jefe internacional de localización
L081=3,Nikolaus Gregorcic
L082=2,Jefe internacional de seguridad y protección
L083=3,Gerhard Neuhofer
L084=2,Director artístico
L085=3,Christian Glatz
L086=2,Artista gráfico
L087=3,Sabine Schmid

L088=4,Equipo de Alemania
L089=2,Director de tecnología
L090=3,Thomas Kirchenkamp
L091=2,Supervisor de producción
L092=3,Boris Kunkel
L093=2,Productor ejecutivo
L094=3,Ralf Adam
L095=2,Productor asociado
L096=3,Thomas B�cker
L097=2,Jefe de marketing de desarrollo
L098=3,Reinhard D�pfer
L099=2,Jefe de producto
L100=3,Gero D�ring
L101=2,Marketing y relaciones públicas
L102=3,Esther Manga
L103=2,Ayudante de relaciones públicas
L104=3,J�rgen Kroder
L105=2,Jefe de control de calidad
L106=3,Gregor Wilkenloh
L107=2,Probadores jefes
L108=3,Gregor Wilkenloh
L109=3,Nicolai Porsche

L110=2,Probadores
L111=3,Arshia �Fahri� Nasserzadeh 
L112=3,Andreas Wiederspahn
L113=3,Bastian Kohsow
L114=3,Frank Mlynek
L115=3,Gerrit Hansen
L116=3,Gregor Plohl
L117=3,Holger Naumann
L118=3,Joannis Thomas
L119=3,Marcus Beck
L120=3,Mario Carl
L121=3,Dirk Meinecke
L122=3,Marc Reinfelder
L123=3,Ulf Riediger
L124=3,Viktor Bremer
