[MAIN]

[menu]
music = menu

[credits]
;credits :)
music = Credits
volume = 0

[lev_baza_des]
;Bunker
music_slow=desert
music_fast=desert_f
SLOW_LOOP_START = 0:0.0
FAST_LOOP_START = 0:0.0

SwitchToSlowSlowStep = 1
SwitchToSlowDelay = 100
; will be -5000
SwitchToSlowFastStopLevel = 5000
; will be -1
SwitchToSlowFastStep = 1
; will be -2000
SwitchToSlowSlowStartVolume = 2000

[lev_china_mafia]
;Chintatown
music_slow=chinatown
music_fast=chinatown_f
SLOW_LOOP_START = 0:0.0
FAST_LOOP_START = 0:42.681

SwitchToSlowSlowStep = 1
SwitchToSlowDelay = 100
; will be -5000
SwitchToSlowFastStopLevel = 5000
; will be -1
SwitchToSlowFastStep = 1
; will be -2000
SwitchToSlowSlowStartVolume = 2000

[lev_lot_guatemala]
;Yapala-Guatemala
music_slow=guatemala
music_fast=guatemala_f
SLOW_LOOP_START = 0:0.0
FAST_LOOP_START = 0:0.0

SwitchToSlowSlowStep = 1
SwitchToSlowDelay = 100
; will be -5000
SwitchToSlowFastStopLevel = 5000
; will be -1
SwitchToSlowFastStep = 1
; will be -2000
SwitchToSlowSlowStartVolume = 2000

[lev_warehouse]
;Spedition
music_slow=warehouse
music_fast=warehouse_f
SLOW_LOOP_START = 0:0.0
FAST_LOOP_START = 0:0.0

SwitchToSlowSlowStep = 1
SwitchToSlowDelay = 100
; will be -5000
SwitchToSlowFastStopLevel = 5000
; will be -1
SwitchToSlowFastStep = 1
; will be -2000
SwitchToSlowSlowStartVolume = 2000

[lev_el_hakero]
;El Coro - Mexiko
music_slow=mexico
music_fast=mexico_f
SLOW_LOOP_START = 0:0.0
FAST_LOOP_START = 0:0.0

SwitchToSlowSlowStep = 1
SwitchToSlowDelay = 100
; will be -5000
SwitchToSlowFastStopLevel = 5000
; will be -1
SwitchToSlowFastStep = 1
; will be -2000
SwitchToSlowSlowStartVolume = 2000

[lev_hideout]
;Hafenviertel
music_slow=metro
music_fast=metro_f
SLOW_LOOP_START = 0:0.0
FAST_LOOP_START = 0:0.0

SwitchToSlowSlowStep = 1
SwitchToSlowDelay = 100
; will be -5000
SwitchToSlowFastStopLevel = 5000
; will be -1
SwitchToSlowFastStep = 1
; will be -2000
SwitchToSlowSlowStartVolume = 2000

[lev_campsite]
;Wohnwagen
music_slow=mexico
music_fast=mexico_f
SLOW_LOOP_START = 0:0.0
FAST_LOOP_START = 0:0.0

SwitchToSlowSlowStep = 1
SwitchToSlowDelay = 100
; will be -5000
SwitchToSlowFastStopLevel = 5000
; will be -1
SwitchToSlowFastStep = 1
; will be -2000
SwitchToSlowSlowStartVolume = 2000

[lev_shark_mission]
;Fischverladestelle
music_slow=harbor
music_fast=guatemala_f
SLOW_LOOP_START = 0:0.0
FAST_LOOP_START = 0:0.0

SwitchToSlowSlowStep = 1
SwitchToSlowDelay = 100
; will be -5000
SwitchToSlowFastStopLevel = 5000
; will be -1
SwitchToSlowFastStep = 1
; will be -2000
SwitchToSlowSlowStartVolume = 2000

[lev_baza_des2]
;Ausbildungscamp
music_slow=desert
music_fast=desert_f
SLOW_LOOP_START = 0:0.0
FAST_LOOP_START = 0:0.0

SwitchToSlowSlowStep = 1
SwitchToSlowDelay = 100
; will be -5000
SwitchToSlowFastStopLevel = 5000
; will be -1
SwitchToSlowFastStep = 1
; will be -2000
SwitchToSlowSlowStartVolume = 2000

[lev_docks]
;Buero
music_slow=silent
music_fast=silent_f
SLOW_LOOP_START = 0:0.0
FAST_LOOP_START = 0:0.0

SwitchToSlowSlowStep = 1
SwitchToSlowDelay = 100
; will be -5000
SwitchToSlowFastStopLevel = 5000
; will be -1
SwitchToSlowFastStep = 1
; will be -2000
SwitchToSlowSlowStartVolume = 2000

[lev_fabryka_des]
;Trakt
music_slow=mine
music_fast=mine_f
SLOW_LOOP_START = 0:0.0
FAST_LOOP_START = 0:0.0

SwitchToSlowSlowStep = 1
SwitchToSlowDelay = 100
; will be -5000
SwitchToSlowFastStopLevel = 5000
; will be -1
SwitchToSlowFastStep = 1
; will be -2000
SwitchToSlowSlowStartVolume = 2000

[lev_hazienda]
;Hazienda
music_slow=jungle
music_fast=jungle_f
SLOW_LOOP_START = 0:0.0
FAST_LOOP_START = 0:28.396

SwitchToSlowSlowStep = 1
SwitchToSlowDelay = 100
; will be -5000
SwitchToSlowFastStopLevel = 5000
; will be -1
SwitchToSlowFastStep = 1
; will be -2000
SwitchToSlowSlowStartVolume = 2000

[lev_laboratory]
music_slow=mine
music_fast=mine_f
SLOW_LOOP_START = 0:0.0
FAST_LOOP_START = 0:0.0

SwitchToSlowSlowStep = 1
SwitchToSlowDelay = 100
; will be -5000
SwitchToSlowFastStopLevel = 5000
; will be -1
SwitchToSlowFastStep = 1
; will be -2000
SwitchToSlowSlowStartVolume = 2000

[lev_mag_bio_las]
;Dikowsk-Russland
music_slow=camp
music_fast=silent_f
SLOW_LOOP_START = 0:0.0
FAST_LOOP_START = 0:0.0

SwitchToSlowSlowStep = 1
SwitchToSlowDelay = 100
; will be -5000
SwitchToSlowFastStopLevel = 5000
; will be -1
SwitchToSlowFastStep = 1
; will be -2000
SwitchToSlowSlowStartVolume = 2000

[lev_marksboss]
;Antiirgendwas-Mexiko
music_slow=harbor
music_fast=silent_f
SLOW_LOOP_START = 0:0.0
FAST_LOOP_START = 0:0.0

SwitchToSlowSlowStep = 1
SwitchToSlowDelay = 100
; will be -5000
SwitchToSlowFastStopLevel = 5000
; will be -1
SwitchToSlowFastStep = 1
; will be -2000
SwitchToSlowSlowStartVolume = 2000

[lev_metro]
;Metrostation
music_slow=metro
music_fast=metro_f
SLOW_LOOP_START = 0:0.0
FAST_LOOP_START = 0:0.0

SwitchToSlowSlowStep = 1
SwitchToSlowDelay = 100
; will be -5000
SwitchToSlowFastStopLevel = 5000
; will be -1
SwitchToSlowFastStep = 1
; will be -2000
SwitchToSlowSlowStartVolume = 2000

[lev_mine]
;Berkwerk
music_slow=mine
music_fast=mine_f
SLOW_LOOP_START = 0:0.0
FAST_LOOP_START = 0:0.0

SwitchToSlowSlowStep = 1
SwitchToSlowDelay = 100
; will be -5000
SwitchToSlowFastStopLevel = 5000
; will be -1
SwitchToSlowFastStep = 1
; will be -2000
SwitchToSlowSlowStartVolume = 2000
