;----------------------------------------------
; Kursory 0-30 sa systemowe, od 31 w gore definiowane dla broni itp. 
;
;----------------------------------------------
; LICZBA KURSORÓW !!!!!!!!!!!!!!!!!!!!!!!
[main]
nocursors = 38
;----------------------------------------------
; Defaultowy (jesli nie znajdzie innego to ten)
; TARGETING_STANDARD   0
;[cursor_0]
;id = 0
;type = 1
;pointtype = 0
;texturename_0 = cel_bad
[cursor_0]
id = 0
type = 1
pointtype = 0
notextures = 6
animtime = 1
texturename_0 = nw0000
texturename_1 = nw0001
texturename_2 = nw0002
texturename_3 = nw0003
texturename_4 = nw0004
texturename_5 = nw0005
;----------------------------------------------
; TARGETING_NONE 1 //No Way
[cursor_1]
id = 1
type = 0
pointtype = 0
notextures = 6
animtime = 1
texturename_0 = nw0000
texturename_1 = nw0001
texturename_2 = nw0002
texturename_3 = nw0003
texturename_4 = nw0004
texturename_5 = nw0005
;----------------------------------------------
;TARGETING_HAND  2 // Lapka kiedy przycisk
[cursor_2]
id = 2
type = 0
pointtype = 0
notextures = 6
animtime = 2
texturename_0 = bonus0000
texturename_1 = bonus0001
texturename_2 = bonus0002
texturename_3 = bonus0003
texturename_4 = bonus0004
texturename_5 = bonus0005
;----------------------------------------------
;TARGETING_HUMAN 3 // Na czlowieka - mordka
[cursor_3]
id = 3
type = 0
pointtype = 0
notextures = 6
animtime = 3
texturename_0 = talk0000
texturename_1 = talk0001
texturename_2 = talk0002
texturename_3 = talk0003
texturename_4 = talk0004
texturename_5 = talk0005
;----------------------------------------------
; TARGETING_ARROW_GAMEBAR 4 //game bar cursor
[cursor_4]
id = 4
type = 1
pointtype = 1
texturename_0 = kur6_001
;----------------------------------------------
;TARGETING_LOCKED_M  5 // zamek mechaniczny
[cursor_5]
id = 5
type = 1
pointtype = 0
texturename_0 = lapka_niebieska
;----------------------------------------------
;TARGETING_LOCKED_E  6 // zamek elektryczny
[cursor_6]
id = 6
type = 1
pointtype = 0
texturename_0 = lapka_niebieska
;----------------------------------------------
;TARGETING_LOCKED_3  7 // 3 proby wlamania
[cursor_7]
id = 7
type = 1
pointtype = 0
texturename_0 = lock_m
;----------------------------------------------
;TARGETING_MINE      8 // Rozbrajanie miny
[cursor_8]
id = 8
type = 1
pointtype = 0
texturename_0 = cel_bad
;----------------------------------------------
; TARGETING_MAYWALK  9 // Moze isc
[cursor_9]
id = 9
type = 0
pointtype = 0
notextures = 6
animtime = 1
texturename_0 = cw0000
texturename_1 = cw0001
texturename_2 = cw0002
texturename_3 = cw0003
texturename_4 = cw0004
texturename_5 = cw0005
;----------------------------------------------
; Podnoszenie trupa
[cursor_10]
id = 10
type = 0
pointtype = 0
notextures = 11
animtime = 1
texturename_0 = body01
texturename_1 = body02
texturename_2 = body03
texturename_3 = body04
texturename_4 = body05
texturename_5 = body06
texturename_6 = body07
texturename_7 = body08
texturename_8 = body09
texturename_9 = body10
texturename_10 = body11
; ------------ Scroll Ekranu -------------------
;---- UP
[cursor_11]
id = 11
type = 0
pointtype = 0
notextures = 8
animtime = 1
texturename_0 = ar_up1
texturename_1 = ar_up2
texturename_2 = ar_up3
texturename_3 = ar_up4
texturename_4 = ar_up5
texturename_5 = ar_up6
texturename_6 = ar_up7
texturename_7 = ar_up8
;---- DOWN
[cursor_12]
id = 12
type = 0
pointtype = 0
notextures = 8
animtime = 1
texturename_0 = ar_down1
texturename_1 = ar_down2
texturename_2 = ar_down3
texturename_3 = ar_down4
texturename_4 = ar_down5
texturename_5 = ar_down6
texturename_6 = ar_down7
texturename_7 = ar_down8
;---- LEFT
[cursor_13]
id = 13
type = 0
pointtype = 0
notextures = 8
animtime = 1
texturename_0 = ar_left1
texturename_1 = ar_left2
texturename_2 = ar_left3
texturename_3 = ar_left4
texturename_4 = ar_left5
texturename_5 = ar_left6
texturename_6 = ar_left7
texturename_7 = ar_left8

;---- RIGHT
[cursor_14]
id = 14
type = 0
pointtype = 0
notextures = 8
animtime = 1
texturename_0 = ar_right1
texturename_1 = ar_right2
texturename_2 = ar_right3
texturename_3 = ar_right4
texturename_4 = ar_right5
texturename_5 = ar_right6
texturename_6 = ar_right7
texturename_7 = ar_right8
;---- UPLEFT
[cursor_15]
id = 15
type = 1
pointtype = 0
texturename_0 = cel_bad

;---- UPRIGHT
[cursor_16]
id = 16
type = 1
pointtype = 0
texturename_0 = cel_bad
;---- DOWNLEFT
[cursor_17]
id = 17
type = 1
pointtype = 0
texturename_0 = cel_bad
;---- DOWNRIGHT
[cursor_18]
id = 18
type = 1
pointtype = 0
texturename_0 = cel_bad
; -------------------------------
; TARGETING_ASTAR_CALC 19 // ASTAR LICZY
[cursor_19]
id = 19
type = 0
pointtype = 0
notextures = 10
animtime = 1
texturename_0 = pol0000
texturename_1 = pol0001
texturename_2 = pol0002
texturename_3 = pol0003
texturename_4 = pol0004
texturename_5 = pol0005
texturename_6 = pol0006
texturename_7 = pol0007
texturename_8 = pol0008
texturename_9 = pol0009
;------- LIFT TOO FAR ----------------------
[cursor_20]
id = 20
type = 0
pointtype = 0
notextures = 6
animtime = 2
texturename_0 = tf0000
texturename_1 = tf0001
texturename_2 = tf0002
texturename_3 = tf0003
texturename_4 = tf0004
texturename_5 = tf0005


;----------------------------------------------
; REZERWA SYSTEMOWA
; CANNOT CLOSE_DOOR
[cursor_21]
id = 21
type = 0
pointtype = 0
notextures = 6
animtime = 1
texturename_0 = stopy1
texturename_1 = stopy2
texturename_2 = stopy3
texturename_3 = stopy4
texturename_4 = stopy5
texturename_5 = stopy6

[cursor_22]
id = 22
type = 1
pointtype = 0
texturename_0 = strafe
[cursor_23]
id = 23
type = 1
pointtype = 0
texturename_0 = back
[cursor_24]
id = 24
type = 0
pointtype = 0
notextures = 8
animtime = 1
texturename_0 = eng0000
texturename_1 = eng0001
texturename_2 = eng0002
texturename_3 = eng0003
texturename_4 = eng0004
texturename_5 = eng0003
texturename_6 = eng0002
texturename_7 = eng0001
[cursor_25]
id = 25
type = 1
pointtype = 0
texturename_0 = cel_bad
[cursor_26]
id = 26
type = 1
pointtype = 0
texturename_0 = cel_bad
[cursor_27]
id = 27
type = 1
pointtype = 0
texturename_0 = cel_bad
[cursor_28]
id = 28
type = 1
pointtype = 0
texturename_0 = cel_bad
[cursor_29]
id = 29
type = 1
pointtype = 0
texturename_0 = cel_bad
[cursor_30]
id = 30
type = 1
pointtype = 0
texturename_0 = cel_bad

;-------- KONIEC SYSTEMOWYCH -----------------
;---------------------------------------------

;---------------------------------------------
; --------------- BRONIE i LIFT'y ------------

;--------------------?????
[cursor_31]
id = 31
type = 2
pointtype = 0
notextures = 6
animtime = 1
texturename_0 = cel0004
texturename_1 = cel0003
texturename_2 = cel0002
texturename_3 = cel0001
texturename_4 = cel0000
texturename_5 = cel_noway
;---------------????????????????
[cursor_32]
id = 32
type = 0
pointtype = 0
notextures = 4
animtime = 1
texturename_0 = pistol1
texturename_1 = pistol2
texturename_2 = pistol3
texturename_3 = pistol2

;----------------------- przeskok (lift)
[cursor_33]
id = 33
type = 0
pointtype = 0
notextures = 6
animtime = 1
texturename_0 = jump0000
texturename_1 = jump0001
texturename_2 = jump0002
texturename_3 = jump0003
texturename_4 = jump0004
texturename_5 = jump0005

;-------------------------- wspinaczka (lift)
[cursor_34]
id = 34
type = 0
pointtype = 0
notextures = 6
animtime = 1
texturename_0 = climb0000
texturename_1 = climb0001
texturename_2 = climb0002
texturename_3 = climb0003
texturename_4 = climb0004
texturename_5 = climb0005
;------------------------------------------
[cursor_35]
id = 35
type = 2
pointtype = 0
notextures = 5
animtime = 1
texturename_0 = cel_r_004
texturename_1 = cel_r_010
texturename_2 = cel_r_016
texturename_3 = cel_r_022
texturename_4 = cel13_001
;------------------------------- oko (button)
[cursor_36]
id = 36
type = 1
pointtype = 0
texturename_0 = oko
; 36-> (przy dodawaniu nowych pamietac o zmianie ilosci na samej gorze)
;------------------------------- piesc (button)
[cursor_37]
id = 37
type = 1
pointtype = 0
texturename_0 = Fist
; 36-> (przy dodawaniu nowych pamietac o zmianie ilosci na samej gorze)