; inik okreslajacy przyrost experience playera za okreslone dzialania

;---------------------------------------------------------------------
;BotLifeMultiple       - wartosc mnozona - mnozy sie przez nia zycie bota (maksymalne)
;BotSkillMultiple      - wartosc mnozona - mnozy sie przez nia skill combat
;
;BotWeap_Type_White    - wartosc dodawana - jezeli zabijany bot mial bron typu HAND
;BotWeap_Type_Pistol   - wartosc dodawana - jezeli zabijany bot mial bron typu PISTOL
;BotWeap_Type_SMG      - wartosc dodawana - jezeli zabijany bot mial bron typu SMG
;BotWeap_Type_Riffle   - wartosc dodawana - jezeli zabijany bot mial bron typu RIFFLE
;BotWeap_Type_Snipe    - wartosc dodawana - jezeli zabijany bot mial bron typu SNIPE
;BotWeap_Type_Shotgun  - wartosc dodawana - jezeli zabijany bot mial bron typu SHOTGUN
;
;White_bonus	       - wartosc dodawana - jezeli player zabil/og³uszy³ przy pomocy broni bia³ej
;xxxx_bonus	       - wartosc dodawana - jezeli player zabil przy pomocy broni typu xxxx (patrze default_values)
;
;Mechanical_test       - wartosc mnozona - mnozy sie przez nia poziom trudnosci pulapki
;
;Objective_xx	       - wartosc dodawana w zaleznosci od konkretnego objective'u (numerowane od 1)
;OneBot_OnEndLevel     - wartosc dodana do experience za kazdego zywego bota
;---------------------------------------------------------------------

; UWAGA: jezeli dana wartosc nie wystepuje w sekcji levelu, zostanie pobrana z default_values

[MAIN]
;none

[default_values]

BotLifeMultiple   = 1
BotSkillMultiple  = 2

BotWeap_Type_White    = 3
BotWeap_Type_Pistol   = 5
BotWeap_Type_SMG      = 10
BotWeap_Type_Riffle   = 15
BotWeap_Type_Snipe    = 20
BotWeap_Type_Shotgun  = 25

Mechanical_test = 10

Objective_1 = 10
Objective_2 = 20
Objective_3 = 30
Objective_4 = 40

White_bonus 	= 50
Pistol_bonus 	= 0
SMG_bonus 	= 0
Riffle_bonus 	= 0
Snipe_bonus 	= 0 
Shotgun_bonus 	= 0
Heavy_bonus 	= 0
Launcher_bonus 	= 0

OneBot_OnEndLevel = 50


[Test_Field]

BotLifeMultiple   = 1
BotSkillMultiple  = 2

BotWeap_Type_White    = 3
BotWeap_Type_Pistol   = 5
BotWeap_Type_SMG      = 10
BotWeap_Type_Riffle   = 15
BotWeap_Type_Snipe    = 20
BotWeap_Type_Shotgun  = 25

Mechanical_test = 10

Objective_1 = 10
Objective_2 = 20
Objective_3 = 30
Objective_4 = 40

White_bonus 	= 50
Pistol_bonus 	= 0
SMG_bonus 	= 0
Riffle_bonus 	= 0
Snipe_bonus 	= 0 
Shotgun_bonus 	= 0
Heavy_bonus 	= 0
Launcher_bonus 	= 0

OneBot_OnEndLevel = 50

[Lev_Baza_Des]

BotLifeMultiple   = 1
BotSkillMultiple  = 2

BotWeap_Type_White    = 3
BotWeap_Type_Pistol   = 5
BotWeap_Type_SMG      = 10
BotWeap_Type_Riffle   = 15
BotWeap_Type_Snipe    = 20
BotWeap_Type_Shotgun  = 25

Mechanical_test = 10

Objective_1 = 10
Objective_2 = 20
Objective_3 = 30
Objective_4 = 40

White_bonus 	= 50
Pistol_bonus 	= 0
SMG_bonus 	= 0
Riffle_bonus 	= 0
Snipe_bonus 	= 0 
Shotgun_bonus 	= 0
Heavy_bonus 	= 0
Launcher_bonus 	= 0

OneBot_OnEndLevel = 50

[Lev_campsite]

BotLifeMultiple   = 1
BotSkillMultiple  = 2

BotWeap_Type_White    = 3
BotWeap_Type_Pistol   = 5
BotWeap_Type_SMG      = 10
BotWeap_Type_Riffle   = 15
BotWeap_Type_Snipe    = 20
BotWeap_Type_Shotgun  = 25

Mechanical_test = 10

Objective_1 = 10
Objective_2 = 20
Objective_3 = 30
Objective_4 = 40

White_bonus 	= 50
Pistol_bonus 	= 0
SMG_bonus 	= 0
Riffle_bonus 	= 0
Snipe_bonus 	= 0 
Shotgun_bonus 	= 0
Heavy_bonus 	= 0
Launcher_bonus 	= 0

OneBot_OnEndLevel = 50

[Lev_China_mafia]

BotLifeMultiple   = 1
BotSkillMultiple  = 2

BotWeap_Type_White    = 3
BotWeap_Type_Pistol   = 5
BotWeap_Type_SMG      = 10
BotWeap_Type_Riffle   = 15
BotWeap_Type_Snipe    = 20
BotWeap_Type_Shotgun  = 25

Mechanical_test = 10

Objective_1 = 10
Objective_2 = 20
Objective_3 = 30
Objective_4 = 40

White_bonus 	= 50
Pistol_bonus 	= 0
SMG_bonus 	= 0
Riffle_bonus 	= 0
Snipe_bonus 	= 0 
Shotgun_bonus 	= 0
Heavy_bonus 	= 0
Launcher_bonus 	= 0

OneBot_OnEndLevel = 50

[Lev_El_hakero]

BotLifeMultiple   = 1
BotSkillMultiple  = 2

BotWeap_Type_White    = 3
BotWeap_Type_Pistol   = 5
BotWeap_Type_SMG      = 10
BotWeap_Type_Riffle   = 15
BotWeap_Type_Snipe    = 20
BotWeap_Type_Shotgun  = 25

Mechanical_test = 10

Objective_1 = 10
Objective_2 = 20
Objective_3 = 30
Objective_4 = 40

White_bonus 	= 50
Pistol_bonus 	= 0
SMG_bonus 	= 0
Riffle_bonus 	= 0
Snipe_bonus 	= 0 
Shotgun_bonus 	= 0
Heavy_bonus 	= 0
Launcher_bonus 	= 0

OneBot_OnEndLevel = 50

[Lev_Fabryka_des]

BotLifeMultiple   = 1
BotSkillMultiple  = 2

BotWeap_Type_White    = 3
BotWeap_Type_Pistol   = 5
BotWeap_Type_SMG      = 10
BotWeap_Type_Riffle   = 15
BotWeap_Type_Snipe    = 20
BotWeap_Type_Shotgun  = 25

Mechanical_test = 10

Objective_1 = 10
Objective_2 = 20
Objective_3 = 30
Objective_4 = 40

White_bonus 	= 50
Pistol_bonus 	= 0
SMG_bonus 	= 0
Riffle_bonus 	= 0
Snipe_bonus 	= 0 
Shotgun_bonus 	= 0
Heavy_bonus 	= 0
Launcher_bonus 	= 0

OneBot_OnEndLevel = 50

[LEV_Hazienda]

BotLifeMultiple   = 1
BotSkillMultiple  = 2

BotWeap_Type_White    = 3
BotWeap_Type_Pistol   = 5
BotWeap_Type_SMG      = 10
BotWeap_Type_Riffle   = 15
BotWeap_Type_Snipe    = 20
BotWeap_Type_Shotgun  = 25

Mechanical_test = 10

Objective_1 = 10
Objective_2 = 20
Objective_3 = 30
Objective_4 = 40

White_bonus 	= 50
Pistol_bonus 	= 0
SMG_bonus 	= 0
Riffle_bonus 	= 0
Snipe_bonus 	= 0 
Shotgun_bonus 	= 0
Heavy_bonus 	= 0
Launcher_bonus 	= 0

OneBot_OnEndLevel = 50

[Lev_hideout]

BotLifeMultiple   = 1
BotSkillMultiple  = 2

BotWeap_Type_White    = 3
BotWeap_Type_Pistol   = 5
BotWeap_Type_SMG      = 10
BotWeap_Type_Riffle   = 15
BotWeap_Type_Snipe    = 20
BotWeap_Type_Shotgun  = 25

Mechanical_test = 10

Objective_1 = 10
Objective_2 = 20
Objective_3 = 30
Objective_4 = 40

White_bonus 	= 50
Pistol_bonus 	= 0
SMG_bonus 	= 0
Riffle_bonus 	= 0
Snipe_bonus 	= 0 
Shotgun_bonus 	= 0
Heavy_bonus 	= 0
Launcher_bonus 	= 0

OneBot_OnEndLevel = 50

[Lev_laboratory]

BotLifeMultiple   = 1
BotSkillMultiple  = 2

BotWeap_Type_White    = 3
BotWeap_Type_Pistol   = 5
BotWeap_Type_SMG      = 10
BotWeap_Type_Riffle   = 15
BotWeap_Type_Snipe    = 20
BotWeap_Type_Shotgun  = 25

Mechanical_test = 10

Objective_1 = 10
Objective_2 = 20
Objective_3 = 30
Objective_4 = 40

White_bonus 	= 50
Pistol_bonus 	= 0
SMG_bonus 	= 0
Riffle_bonus 	= 0
Snipe_bonus 	= 0 
Shotgun_bonus 	= 0
Heavy_bonus 	= 0
Launcher_bonus 	= 0

OneBot_OnEndLevel = 50

[Lev_lot_guatemala]

BotLifeMultiple   = 1
BotSkillMultiple  = 2

BotWeap_Type_White    = 3
BotWeap_Type_Pistol   = 5
BotWeap_Type_SMG      = 10
BotWeap_Type_Riffle   = 15
BotWeap_Type_Snipe    = 20
BotWeap_Type_Shotgun  = 25

Mechanical_test = 10

Objective_1 = 10
Objective_2 = 20
Objective_3 = 30
Objective_4 = 40

White_bonus 	= 50
Pistol_bonus 	= 0
SMG_bonus 	= 0
Riffle_bonus 	= 0
Snipe_bonus 	= 0 
Shotgun_bonus 	= 0
Heavy_bonus 	= 0
Launcher_bonus 	= 0

OneBot_OnEndLevel = 50

[Lev_Mag_bio_las]

BotLifeMultiple   = 1
BotSkillMultiple  = 2

BotWeap_Type_White    = 3
BotWeap_Type_Pistol   = 5
BotWeap_Type_SMG      = 10
BotWeap_Type_Riffle   = 15
BotWeap_Type_Snipe    = 20
BotWeap_Type_Shotgun  = 25

Mechanical_test = 10

Objective_1 = 10
Objective_2 = 20
Objective_3 = 30
Objective_4 = 40

White_bonus 	= 50
Pistol_bonus 	= 0
SMG_bonus 	= 0
Riffle_bonus 	= 0
Snipe_bonus 	= 0 
Shotgun_bonus 	= 0
Heavy_bonus 	= 0
Launcher_bonus 	= 0

OneBot_OnEndLevel = 50

[Lev_marksboss]

BotLifeMultiple   = 1
BotSkillMultiple  = 2

BotWeap_Type_White    = 3
BotWeap_Type_Pistol   = 5
BotWeap_Type_SMG      = 10
BotWeap_Type_Riffle   = 15
BotWeap_Type_Snipe    = 20
BotWeap_Type_Shotgun  = 25

Mechanical_test = 10

Objective_1 = 10
Objective_2 = 20
Objective_3 = 30
Objective_4 = 40

White_bonus 	= 50
Pistol_bonus 	= 0
SMG_bonus 	= 0
Riffle_bonus 	= 0
Snipe_bonus 	= 0 
Shotgun_bonus 	= 0
Heavy_bonus 	= 0
Launcher_bonus 	= 0

OneBot_OnEndLevel = 50

[Lev_Metro]

BotLifeMultiple   = 1
BotSkillMultiple  = 2

BotWeap_Type_White    = 3
BotWeap_Type_Pistol   = 5
BotWeap_Type_SMG      = 10
BotWeap_Type_Riffle   = 15
BotWeap_Type_Snipe    = 20
BotWeap_Type_Shotgun  = 25

Mechanical_test = 10

Objective_1 = 10
Objective_2 = 20
Objective_3 = 30
Objective_4 = 40

White_bonus 	= 50
Pistol_bonus 	= 0
SMG_bonus 	= 0
Riffle_bonus 	= 0
Snipe_bonus 	= 0 
Shotgun_bonus 	= 0
Heavy_bonus 	= 0
Launcher_bonus 	= 0

OneBot_OnEndLevel = 50

[Lev_mine]

BotLifeMultiple   = 1
BotSkillMultiple  = 2

BotWeap_Type_White    = 3
BotWeap_Type_Pistol   = 5
BotWeap_Type_SMG      = 10
BotWeap_Type_Riffle   = 15
BotWeap_Type_Snipe    = 20
BotWeap_Type_Shotgun  = 25

Mechanical_test = 10

Objective_1 = 10
Objective_2 = 20
Objective_3 = 30
Objective_4 = 40

White_bonus 	= 50
Pistol_bonus 	= 0
SMG_bonus 	= 0
Riffle_bonus 	= 0
Snipe_bonus 	= 0 
Shotgun_bonus 	= 0
Heavy_bonus 	= 0
Launcher_bonus 	= 0

OneBot_OnEndLevel = 50

[Lev_shark_mission]

BotLifeMultiple   = 1
BotSkillMultiple  = 2

BotWeap_Type_White    = 3
BotWeap_Type_Pistol   = 5
BotWeap_Type_SMG      = 10
BotWeap_Type_Riffle   = 15
BotWeap_Type_Snipe    = 20
BotWeap_Type_Shotgun  = 25

Mechanical_test = 10

Objective_1 = 10
Objective_2 = 20
Objective_3 = 30
Objective_4 = 40

White_bonus 	= 50
Pistol_bonus 	= 0
SMG_bonus 	= 0
Riffle_bonus 	= 0
Snipe_bonus 	= 0 
Shotgun_bonus 	= 0
Heavy_bonus 	= 0
Launcher_bonus 	= 0

OneBot_OnEndLevel = 50

[Lev_warehouse]

BotLifeMultiple   = 1
BotSkillMultiple  = 2

BotWeap_Type_White    = 3
BotWeap_Type_Pistol   = 5
BotWeap_Type_SMG      = 10
BotWeap_Type_Riffle   = 15
BotWeap_Type_Snipe    = 20
BotWeap_Type_Shotgun  = 25

Mechanical_test = 10

Objective_1 = 10
Objective_2 = 20
Objective_3 = 30
Objective_4 = 40

White_bonus 	= 50
Pistol_bonus 	= 0
SMG_bonus 	= 0
Riffle_bonus 	= 0
Snipe_bonus 	= 0 
Shotgun_bonus 	= 0
Heavy_bonus 	= 0
Launcher_bonus 	= 0

OneBot_OnEndLevel = 50

