[MAIN]

;Strings to display on screen
Map_time = Map time left:
Round_time = Round time left:
Money = Cash:
Buy_time = Buying time left:
Freeze_time = Freeze time left:

; ilosc map nie jest nigdzie okreslona, program bedzie 
; przechodzil kazda po kolei, a po ostatniej wroci do pierwszej
; format klucza musi byc:
; Map_xx=NAZWA_MAPY, gdzie xx oznacza kolejny numer

; VIP ESCAPE
[MAPS_VE] 
Map_0=MP\LEV_FABRYKA_DES_MP
Map_1=MP\LEV_HIDEOUT_MP
Map_2=MP\LEV_WAREHOUSE_MP
Map_3=MP\LEV_METRO_MP
Map_4=MP\LEV_CAMPSITE_MP
Map_5=MP\LEV_EL_HAKERO_MP
Map_6=MP\LEV_LOT_GUATEMALA_MP
Map_7=MP\LEV_MARKSBOSS_MP

; TERRORIST ESCAPE
[MAPS_TE]
Map_0=MP\LEV_FABRYKA_DES_MP
Map_1=MP\LEV_HIDEOUT_MP
Map_2=MP\LEV_WAREHOUSE_MP
Map_3=MP\LEV_METRO_MP
Map_4=MP\LEV_CAMPSITE_MP
Map_5=MP\LEV_EL_HAKERO_MP
Map_6=MP\LEV_LOT_GUATEMALA_MP
Map_7=MP\LEV_MARKSBOSS_MP

; Suitcase
[MAPS_SC]
Map_0=MP\LEV_FABRYKA_DES_MP
Map_1=MP\LEV_HIDEOUT_MP
Map_2=MP\LEV_WAREHOUSE_MP
Map_3=MP\LEV_METRO_MP
Map_4=MP\LEV_CAMPSITE_MP
Map_5=MP\LEV_EL_HAKERO_MP
Map_6=MP\LEV_LOT_GUATEMALA_MP
Map_7=MP\LEV_MARKSBOSS_MP

[SKINS]
skins=9
skin_0=HUM_Mcafr_Hazard.x
skin_1=mcafr_bial.x
skin_2=HUM_Mcafr_Pracownik01.x
skin_3=HUM_MCAFR_02_police.x
skin_4=HUM_Mcafr_Hazard.x
skin_5=HUM_MCAFR_01_black.x
skin_6=HUM_MCAFR_01_pust.x
skin_7=HUM_MCAFR_01_las.x
skin_8=HUM_MCAFR_03.x


[DEFAULT_SERVER]
; Servername
Server_Name=Cold Zero MP Server

; Anzahl der durch ein Team gewonnener Runden, nach der eine neue Map automatisch geladen wird
; Wenn 0 wird nie eine neue Map automatisch geladen
Win_Limit=20

; Anzahl der Runden, nach der eine neue Map automatisch geladen wird
; Wenn 0 wird nie eine neue Map automatisch geladen
Round_Limit=0

; Zeit, nach der eine neue Map automatisch geladen wird
; Wenn 0 wird nie eine neue Map automatisch geladen
Map_Time=15

; Zeit, wie lange eine Runde dauern soll
; Wenn 0, erfolgt kein Rundenrestart
Round_Time=10

; Zeit, in der Spieler sich nicht bewegen und schießen, sondern ausschließlich kaufen können
; Wenn 0 dann keine FreezeTime
Freeze_Time=5

; Zeit, in der man Waffen und Munition kaufen kann
; Wenn 0, kann während der ganzen Runde gekauft werden
Buy_Time=90

; Ein- und Ausschalten von Friendly Fire ( 0 - aus, 1 - ein )
Friendly_Fire=1

; czy zabijanie TK w nowej rundzie jest dozwolone ( 0 - nie, 1 - tak )
Kill_TK=1

; czy wyrzucanie nieaktywnych graczy jest dozwolone ( 0 - nie, 1 - tak )
Kick_Idle=1

; tryb kamery dla SpectateMode ( 0 - Free, 1 - SpectateAll, 2 - SpectateTeamOnly, 3 - FadeToBlack )
Death_Camera_Mode=0

; czy wyrzucanie TK po x razach (TK) jest mozliwe ( x czytane stad, jezeli== 0, nie jest mozliwe, jezeli 1, od razu i tak dalej... )
Kick_TK=0

; czy mozliwe jest usuwanie botow, aby zwolnic sloty dla nowych graczy ( 0 - nie, 1 - tak )
Kick_Bot_Enable=0

; Tryb wyswietlania imion
ShowNames_Mode=2

; maksymalna ilosc graczy ( nie moze byc 0, jezeli, zmieniana na 1 ), jezeli > 16, zmieniane na 16
Max_Players=16

; maksymalna ilosc botow ( jezeli 0, boty na stale wylaczone )
Max_Bots=0

; startowa ilosc pieniedzy
Starting_Money=4000

; kaska przyznawana na NEW_ROUND wszystkim graczom 
Money_For_All=1000

; kaska przyznawana na NEW_ROUND zwyciêzcom
Money_For_Winners=1000

; kaska przyznawana graczowi za jednego fraga
Money_For_Frag=500

; kaska przyznawana terroryscie za ucieczke
Money_For_Terrorist_who_escape=1000



[DEFAULT_BOTS_NAMES]
Bot_00=John
Bot_01=Jack
Bot_02=Nathan
Bot_03=Madafaka
Bot_04=Badboy
Bot_05=Utini
Bot_06=Rambo
Bot_07=Uga
Bot_08=Kenny
Bot_09=Cartman
Bot_10=Bill
Bot_11=Chief
Bot_12=Soldat
Bot_13=Marty
Bot_14=Dobberman
Bot_15=Johnny

