; -------sound of steps, definitions of materials, corelations with colours----------

;definition of one sound:
;color on the map:
;R 	- red
;G 	- green
;B 	- blue
; SoundLevel = 100 - WARTOSC DEFAULT

[MAIN]
;number of sounds
;note: always will be reading 8 sounds
Number=5

[sound_0]
;;;SOUND: asfalt
R 	= 255
G 	= 255
B 	= 0
SoundLevel = 100

[sound_1]
;;;SOUND: piasek/dywan
R 	= 153
G 	= 51
B 	= 0
SoundLevel = 50

[sound_2]
;;;SOUND: trawa
R 	= 255
G 	= 150
B 	= 0
SoundLevel = 60

[sound_3]
;;;SOUND: metal
R 	= 0
G 	= 255
B 	= 0
SoundLevel = 150

[sound_4]
;;;SOUND: metal_big - metal????? g³oœniejszy
R 	= 101
G 	= 28
B 	= 0
SoundLevel = 200

[sound_5]
;;;SOUND: plyta chodnikowa/stone
R 	= 255
G 	= 0
B 	= 0
SoundLevel = 120

[sound_6]
;;;SOUND: stone_rev ???? nikt nie wie co to jest - kamienie z echem
R 	= 101
G 	= 28
B 	= 0
SoundLevel = 150

;[sound_7] 
;;;SOUND: wet
;R 	= 101
;G 	= 28
;B 	= 0
SoundLevel = 130

[sound_8]
;;;SOUND: drewno
R 	= 101
G 	= 28
B 	= 0
SoundLevel = 80